# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
plugins: [jekyll-paginate]

title: 雄猫的踩坑日记
url: http://vastzod.xyz
feed: /atom.xml
author_info: <a href="http://vastzod.xyz/">雄猫</a>

myblog:
  gavatar: images/1.jpg
  gpname: 雄猫
  github: https://github.com/Catname
  email: mailto:tomcath@foxmail.com
  coverimgs: []
  postbgimg: []

categories: [note, share, resume]
