# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: 雄猫的自由空间
url: http://catname.github.io
feed: /atom.xml
author_info: <a href="http://catname.github.io/">雄猫</a>

myblog:
  gavatar: images/IMG_6852.GIF
  gpname: 雄猫
  github: https://github.com/Catname
  email: mailto:tomcath@foxmail.com
  coverimgs: []
  postbgimg: []

categories: [记录, 分享]
